name: little_pet_home
description: "LittlePetHome - A new Flutter project created with Based."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  based_list: ^1.1.3
  based_splash_page: ^1.0.1
  based_split_view: ^1.0.7
  dart_date: ^1.3.2
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.9
  intl: ^0.18.1
  json_annotation: ^4.8.1
  material_color_utilities: ^0.5.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  system_tray: ^2.0.3
  url_launcher: ^6.2.3
  window_manager: ^0.3.7

  models:
    path: ../models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans/MiSans-Regular.ttf
    - family: CascadiaCodePL
      fonts:
        - asset: assets/fonts/CascadiaCodePL/CascadiaCodePL-Regular.otf

flutter_intl:
  enabled: true
  class_name: L10N
  arb_dir: lib/l10n
  output_dir: lib/l10n
